### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by anderspitman** [fitzgen/generational-arena#15]
Hey @fitzgen, just wanted to say thanks for the very clear and concise description in the readme. I learned something useful!

**Comment by fitzgen** [comment]
Your welcome :) You should watch the recording of the talk! It's even better (and goes further than this crate does): https://www.youtube.com/watch?v=P9u8x13W7UE

**Comment by anderspitman** [comment]
I've seen it but I'm definitely due for a rewatch.
