### ISSUE TITLE
Add a function to create an Index

### ISSUE THREAD

**Issue by AndreaCatania** [fitzgen/generational-arena#21]
I need to create an opaque key.

Would be nice to have the possibility to use a function new to create an `Index`, when you want to deal with opaque indices.

It's unsafe crate IDs out of this crate, so an idea is to create an `unsafe` function.
Something like: `unsafe create(id: u32, version: u32);`

**Comment by fitzgen** [comment]
So you don't want this to actually allocate space for the index or anything like that?

It seems like the APIs you are describing are possible with a new type right now:

```rust
struct ResourceId(Index);
```

What am I missing here?

**Comment by AndreaCatania** [comment]
`ResourceId` is a type defined by the abstraction that I cannot change. Check it here: https://github.com/AndreaCatania/amethyst_phythyst/blob/master/src/objects.rs#L12-L74

**Comment by AndreaCatania** [comment]
@fitzgen also there is a fork of your crate (that for sure you know https://crates.io/crates/typed-generational-arena) that allow me do what I need. But I would like to use directly your crate since I don't really need a new type.

**Comment by AndreaCatania** [comment]
The proposal to fix this issue is this one: https://github.com/fitzgen/generational-arena/pull/22/files
