### ISSUE TITLE
Could we get a constructor for datastructures that know their own index?

### ISSUE THREAD

**Issue by jannickj** [fitzgen/generational-arena#33]
Could we get something like:
```rust
use generational_arena::{Arena, Index};
impl Arena<T> {
    pub fn insert_with(&mut self, create: impl FnOnce(Index) -> T) -> &mut T {
         ... 
     }
}
```

Would this be possible or is there something I haven't considered.

EDIT: _updated code to be closer to std library_
EDIT2:  _Removed horribly unsafe example_

**Comment by fitzgen** [comment]
This seems useful, and I've done [similar things in the past in other crates](https://docs.rs/id-arena/2.2.1/id_arena/struct.Arena.html#method.alloc_with_id). If you make a PR with test coverage, I'm happy to merge it.
