### ISSUE TITLE
Add drain iterator

### ISSUE THREAD

**Issue by djkoloski** [fitzgen/generational-arena#6]
Thanks for putting this awesome crate together, it's been a big help.

I'm using an Arena to store some Vulkan objects that need to be destroyed by the device during Drop. I would use [`iter_mut()`](https://docs.rs/generational-arena/0.1.0/generational_arena/struct.Arena.html#method.iter_mut), but I need to take ownership of the objects as I remove them. [`Vec`](https://doc.rust-lang.org/std/vec/struct.Vec.html) has a nice [`drain()`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.drain) function that returns a [`Drain`](https://doc.rust-lang.org/std/vec/struct.Drain.html) iterator just for a case like this.

Example:
```rust
struct Assets {
    device: vk::Device,
    images: Arena<vk::Image>,
}

impl Drop for Assets {
    fn drop(&mut self) {
        for image in self.images.drain() {
            self.device.destroy_image(image);
        }
        self.device.destroy();
    }
}
```

**Comment by fitzgen** [comment]
I would be happy to merge a pull request that implements this! Please make sure to add test coverage as well :)
